### PR TITLE
Update ixp-member-list.schema.json

### PR DESCRIPTION
**Pull request by Jtorres0077**
Change for Conex - IXP

### CODE REVIEW

**Comment by nickhilliard** [comment]
`ixp-member-list.schema.json` is the general schema for the IXP export schema, applicable to all IXPs, i.e. contains no information which is specific to an individual IXP.

**Comment by Jtorres0077** [comment]
Dear Nick,

Thank you for your reply.

Could you please clarify if the file I uploaded is incorrect? I have
uploaded the information of my IXP, as well as the members that currently
comprise it. If it is only necessary to provide the data of my IXO, I would
be grateful if you could let me know.

Thank you very much for your attention.

Best regards,

**Comment by nickhilliard** [comment]
Hi @Jtorres0077, this isn't the place to publish your IXP information - this github repository specifies the format of the data. If you want to publish your own data, you need to do this on your own web site, i.e. https://conex-ixp.net/.

If you're starting a new IXP, I'd suggest using IXP Manager (www.ixpmanager.org), because this will automatically create an IXP member list export file for you.

**Comment by Jtorres0077** [comment]
Dear Nick,

Thank you for your reply. Yes, that is exactly what we want to do. We have
already filled out the form in IXP Manager to list our members on the site.
Thank you very much for your support.

Best regards

**Pull request closed without merging**
