### PR TITLE
Add as_macro_source field

### PR DESCRIPTION
**Pull request by robertjakub**
Allow to specify the source IRR for an as_macro. It will allow scripts to ask the requested registry for the macro / autnum.

### CODE REVIEW

**Comment by barryo** [comment]
I guess s/IRR source/IRR sources as an array.

Probably using RADB source tags? (c.f. http://www.radb.net/query/?advanced_query=1 ) 

Or pairs: [ 'whois server to use', 'comma,separated,sources' ] ?

**Comment by robertjakub** [comment]
right, It should be an array of strings using the RADB source tags (uppercase?).
We cannot force the whois_server - someone can have a local mirror / copy of the registries and want to use own to resolve the macros.

**Comment by robertjakub** [comment]
when we agree on it - I'll close this pull request and make an another one ((-; just give me "ok" for it ((-;

**Comment by nickhilliard** [comment]
incidentally, this was something we deliberately stayed away from because it's a rat's nest of configuration items.  For full as macro resolution you need:

- separate AS macro data for ipv4 and ipv6
- whois server name
- what whois server protocol the server uses (ripe or irrd)
- a set of sources, probably in list format

**Comment by barryo** [comment]
I'm even wondering why have it here at all tbh. Is this not something that would be more appropriately delegated to PeeringDB? To answer my own question with a counter argument: do networks tend to have different AS macros at different IXs to represent different policies? In my experience they have the same macros, just advertise what they feel appropriate into each IX.

**Comment by robertjakub** [comment]
The support for separate ASmacro is already committed in the master branch. forcing the whois.server is a big limitation for me - as I wrote, ones can use own mirror (with the known protocol). the same problem/issue is with PeeringDB - as far I remember there are discussion about the format of the as_macro format (eg: IRR::MACRO) and/or adding a separate field for a source.

The result of cross/wrong registry query can be wrong / incorrect - due to lack of network/origin authorisation at the several IRRs (i.e.: RADB). I found, that some networks (er, anti-ddos solutions) made an object with the more-specific network of my with the wrong/own origin without my authorisation and without my knowledge. 

we can move/delegate this data to PeeringDB - but still, there is a limited support for a macros (one field, networks tend to have different macros for IPv4/IPv6, and/or for IXPs) - but we should move also the as_macro. (and I know, the network without PeeringDB entry is ...). 

maybe the solutions can be making a dictionary of "source|whois server|proto" in the ixp section, and use it in the members list (but what about of cross-registry/souce query?).

**Comment by nickhilliard** [comment]
We've looked at this problem before and have figured that that in order to handle it properly we would need:

- an array of entries of IRRDBs, containing an index, a hostname, the whois protocol supported, the IRRDB source name
- for each ASN connected, an AS macro for each of ipv4 and ipv6
- with each AS macro, an ordered list of irrdb entries from the array defined above.

Without this level of completeness (and corresponding complexity), it's basically not possible to construct reasonable or reproducible filter lists.  Both of these would be targets in terms of what you'd want as a consumer of this data.

When designing the schema, there was a balance to be drawn between utility and completeness, i.e. simplicity and complexity. We just felt that the complexity increase from doing this properly was just too much.

**Pull request closed without merging**
